[package]
name = "shared_common"
version = "0.3.0"
edition = "2021"

[dependencies]
rcgen = { version = "0.13.2", default-features = true, features = ["pem"] }
rustls = { version = "0.23.23", default-features = true, features = [] }
