[package]
name = "shared_common"
version = "0.3.0"
edition = "2021"

[dependencies]
rcgen = { workspace = true, default-features = true, features = ["pem"] }
rustls = { workspace = true, default-features = true, features = [] }
