[package]
name = "easy-photo-backup-server"
version = "0.3.0"
edition = "2021"

[dependencies]
common = { path = "../common" , version = "0.3.0" }
rustls = { version = "0.23.23", default-features = true, features = [] }
