[package]
name = "easy-photo-backup-client-cli"
version = "0.3.0"
edition = "2021"

[dependencies]
shared_common.workspace = true
shared_client.workspace = true
rustls = { workspace = true, default-features = true, features = [] }
