[package]
name = "bstorage_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", default-features = false, features = ["derive", "parsing", "proc-macro", "printing"] }
quote = { version ="1.0", default-features = true }
