[package]
name = "shared_client"
version = "0.4.0"
edition = "2024"

[dependencies]
shared_common.workspace = true
rustls = { workspace = true, features = [] }
bstorage_derive = { path = "../shared_common/bstorage_derive" }
