[package]
name = "shared_client"
version = "0.3.0"
edition = "2024"

[dependencies]
shared_common = { path = "../shared_common", version = "0.3.0" }
rustls = { version = "0.23.23", default-features = true, features = [] }
