[package]
name = "uniffi-bindgen-swift"
version = "0.4.0"
edition = "2021"
publish = false

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[[bin]]
name = "uniffi-bindgen-swift"
path = "src/main.rs"
 